// src/utils/audioMap.js
// AUTO-GENERATED by scripts/generate_audio.js — do not edit by hand.
// Run `npm run generate-audio` to regenerate with API key.

export const audioMap = {
  "Welcome to MultiplyQuest! Ready to master your multiplication facts up to 9×9 and conquer the kingdom? 🚀": "/assets/audio/audio_welcome_to_multiplyquest_ready_to_master_your_mult_0.mp3",
  "If Oliver arranges 7 rows of 8 chairs for the school fair, what is the instant way to find the total chairs without counting one by one?": "/assets/audio/audio_if_oliver_arranges_7_rows_of_8_chairs_for_the_scho_1.mp3",
  "Let's investigate how times tables turn slow counting into instant answers!": "/assets/audio/audio_lets_investigate_how_times_tables_turn_slow_counti_2.mp3",
  "Oliver is setting up chairs for the grand school fair — 7 rows, with 8 chairs in each row. His teacher asks, \"How many chairs in total, Oliver?\" He starts counting one by one… 1, 2, 3… but the fair opens in five minutes!": "/assets/audio/audio_oliver_is_setting_up_chairs_for_the_grand_school_f_3.mp3",
  "Emma rushes over with a big smile. \"You don't need to count them one by one, Oliver! We already know 7 × 8 = 56 from our times tables. 7 equal rows of 8 chairs makes 56 chairs — instantly!\"": "/assets/audio/audio_emma_rushes_over_with_a_big_smile_you_dont_need_to_4.mp3",
  "Toby the Owl swoops down gracefully. \"Here is a magical math secret: the order never changes the product! 7 × 8 and 8 × 7 both equal 56. So whenever you know one fact, you already know its flipped partner for free!\"": "/assets/audio/audio_toby_the_owl_swoops_down_gracefully_here_is_a_magi_5.mp3",
  "Oliver grins and proudly calls back to his teacher: \"56 chairs, all ready to go!\" The school gates open right on time. \"From now on, I will always use multiplication facts instead of slow counting!\"": "/assets/audio/audio_oliver_grins_and_proudly_calls_back_to_his_teacher_6.mp3",
  "Station A: Array and Grid Visualizer! Adjust the row and column sliders to build any multiplication array and watch the total calculate live!": "/assets/audio/audio_station_a_array_and_grid_visualizer_adjust_the_row_7.mp3",
  "Station B: Commutative Flip Lab! Rotate the array 90 degrees to see why A × B always equals B × A, and try decomposing big facts!": "/assets/audio/audio_station_b_commutative_flip_lab_rotate_the_array_90_8.mp3",
  "Station C: Equal Groups and Number Line! Send Toby hopping by equal step sizes along the number line to reach the target!": "/assets/audio/audio_station_c_equal_groups_and_number_line_send_toby_h_9.mp3",
  "Station D: Fact Family Triangle! Explore how multiplication and division are connected in every three-number fact family!": "/assets/audio/audio_station_d_fact_family_triangle_explore_how_multipl_10.mp3",
  "Incredible streak! You're unstoppable! 🔥": "/assets/audio/audio_incredible_streak_youre_unstoppable_11.mp3",
  "Triple strike! Fantastic multiplication recall! ⭐": "/assets/audio/audio_triple_strike_fantastic_multiplication_recall_12.mp3",
  "Spot on! That's correct! 🎉": "/assets/audio/audio_spot_on_thats_correct_13.mp3",
  "Not quite, but good effort! Check the multiplication fact and try again.": "/assets/audio/audio_not_quite_but_good_effort_check_the_multiplication_14.mp3",
  "Here is your first clue! Look at the number groups carefully.": "/assets/audio/audio_here_is_your_first_clue_look_at_the_number_groups__15.mp3",
  "Here is the key clue to solve this fact family!": "/assets/audio/audio_here_is_the_key_clue_to_solve_this_fact_family_16.mp3",
  "District Complete! Awesome job mastering these multiplication facts! 🏆": "/assets/audio/audio_district_complete_awesome_job_mastering_these_mult_17.mp3",
  "The Boss Battle begins! Answer all questions correctly and protect your three lives to claim the district crown! 👑": "/assets/audio/audio_the_boss_battle_begins_answer_all_questions_correc_18.mp3",
  "Victory! You defeated the boss and claimed the golden badge! 🏆": "/assets/audio/audio_victory_you_defeated_the_boss_and_claimed_the_gold_19.mp3",
  "Time to reflect on your multiplication journey! Check your key takeaways and review your scorecard! 📓": "/assets/audio/audio_time_to_reflect_on_your_multiplication_journey_che_20.mp3",
  "Congratulations! You are a certified Multiplication Grand Master! 🏆✨": "/assets/audio/audio_congratulations_you_are_a_certified_multiplication_21.mp3",
};

export default audioMap;
